name: Deploy to EC2 on merge
'on':
  push:
    branches:
      - yml
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: deploy to ec2 
        uses: SiaoChi/friends-app@yml
      - run : cd friends-app
      - run : pwd
      - run : echo 'Try to deploy yml'
        with:
          host: '${{ secrets.HOST_DNS }}'
          username: '${{ secrets.EC2_USERNAME }}'
          key: '${{ secrets.EC2_SSH_KEY }}'
            