name: Deploy to EC2 on merge
'on':
  push:
    branches:
      - yml
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run:  echo Hello from Octo Organization
      - name: Navigate to friends-app directory
        run : cd /home/ubuntu/friends-app
      - name: Switch to the yml branch
        run : git switch yml
      - name: Pull latest changes
        run : git pull
      - name: Run container
        run : docker run -d -p 443:3000 --name friends friends
      - name: Build container
        run : docker build -t friends .
      - name: Deploy to EC2
        uses: SiaoChi/friends-app@yml
        with:
          host: '${{ secrets.HOST_DNS }}'
          username: '${{ secrets.EC2_USERNAME }}'
          key: '${{ secrets.EC2_SSH_KEY }}'