name: Deploy to EC2 on merge
'on':
  push:
    branches:
      - yml
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: deploy to ec2
        uses: SiaoChi/friends-app@yml
        with:
          host: '${{ secrets.HOST_DNS }}'
          username: '${{ secrets.EC2_USERNAME }}'
          key: '${{ secrets.EC2_SSH_KEY }}'
          script: |
            echo "Hello from github action, start deploy main to ec2"
            cd friends-app
            git switch yml
            git pull
            echo "git pull done"
            