name: Deploy to EC2 on merge
'on':
  push:
    branches:
      - yml
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello from Octo Organization
      - name: deploy to ec2
        uses: SiaoChi/friends-app@yml
        with:
          host: '${{ secrets.HOST_DNS }}'
          username: '${{ secrets.EC2_USERNAME }}'
          key: '${{ secrets.EC2_SSH_KEY }}'
          script: |
            echo "Hello from github action, start deploy main to ec2"
            cd /home/ubuntu/friends-app
            git switch main
            git pull
            docker kill friends
            docker rm friends
            docker build -t friends . 
            docker run -d -p 443:3000 --name friends friends
            