name: Deploy to EC2 on merge
'on':
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: deploy to ec2
        uses: appleboy/ssh-action@master
        with:
          host: '${{ secrets.TEST_HOST_DNS }}'
          username: '${{ secrets.EC2_USERNAME }}'
          key: '${{ secrets.EC2_SSH_KEY }}'
          script: |
            echo "Hello from github action, start deploy develop to ec2"
            cd /home/ubuntu/friends-app
            docker system prune -a -f
            docker volume prune -f
            docker-compose down
            git switch develop 
            git pull origin develop
            docker-compose up -d --build
            
            