name: Deploy to EC2 on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deploy to ec2
        uses: SiaoChi/friends-app@main
        with:
          host: '${{ secrets.HOST_DNS }}'
          username: '${{ secrets.EC2_USERNAME }}'
          key: '${{ secrets.EC2_SSH_KEY }}'
          script: |
            pwd
            echo "Hello from github action, start deploy main to ec2"
            git switch main
            git pull
            echo "git pull done"
            docker build -t friends . 
            docker run -d -p 443:3000 --name friends friends